[package]
name    = "tun"
version = "0.4.4"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "TUN device creation and handling."
repository  = "https://github.com/meh/rust-tun"
keywords    = ["tun", "network", "tunnel", "bindings"]

edition = "2018"

[dependencies]
libc        = "0.2"
error-chain = "0.12"

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
ioctl-sys  = "0.5"
mio        = { version = "0.6.21", optional = true }
tokio      = { version = "0.2.1", features = ["io-driver"], optional = true }
tokio-util = { version = "0.2.0", features = [ "codec" ], optional = true }
bytes      = { version = "0.5.2", optional = true }
byteorder  = { version = "1.3.2", optional = true }

[dev-dependencies]
packet     = "0.1"
futures    = "0.3.1"
tokio      = { version = "0.2.1", features = ["full"] }

[features]
async = [ "tokio", "tokio-util", "mio", "bytes", "byteorder" ]

[[example]]
name = "read-async"
required-features = [ "async" ]

[[example]]
name = "read-async-codec"
required-features = [ "async" ]

[[example]]
name = "ping-tun"
required-features = [ "async" ]
